name: dask-mini-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - dask=2022.04.02
  # JupyterLab extension
  - jupyterlab>=3
  - dask-labextension=5.2.0
  - ipywidgets=7.6.5
  - graphviz
  - python-graphviz
  - scikit-learn=1.1.1
  - dask-ml=2022.1.22
  - coiled=0.0.56
